services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    volumes:
      - ./data:/app/data              # Local file storage
      - sqlite_data:/app/             # SQLite database persistence (handles all .db* files)
    expose:
      - "8000"
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:///./joborra.db
      - LOCAL_STORAGE_PATH=/app/data
      - LOCAL_STORAGE_URL_PREFIX=/data
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    expose:
      - "80"
    restart: unless-stopped

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
      - frontend
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  sqlite_data:  # Named volume for SQLite database files
