export const DEGREES: string[] = [
  // Common undergraduate degrees
  "Bachelor of Arts (BA)",
  "Bachelor of Science (BSc)",
  "Bachelor of Engineering (BE)",
  "Bachelor of Engineering (Honours)",
  "Bachelor of Information Technology (BIT)",
  "Bachelor of Computer Science (BCompSc)",
  "Bachelor of Commerce (BCom)",
  "Bachelor of Business (BBus)",
  "Bachelor of Laws (LLB)",
  "Bachelor of Design (BDes)",
  "Bachelor of Education (BEd)",
  "Bachelor of Nursing (BNurs)",
  "Bachelor of Health Science (BHlthSc)",
  // Common postgraduate degrees
  "Master of Science (MSc)",
  "Master of Engineering (MEng)",
  "Master of Information Technology (MIT)",
  "Master of Computer Science (MCompSc)",
  "Master of Data Science (MDS)",
  "Master of Business Administration (MBA)",
  "Master of Commerce (MCom)",
  "Master of Finance (MFin)",
  "Master of Professional Accounting (MPA)",
  "Master of Laws (LLM)",
  // Tech/CS specific specialisations
  "Computer Science",
  "Software Engineering",
  "Data Science",
  "Artificial Intelligence",
  "Cyber Security",
  "Information Systems",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Mechatronics",
  "Biomedical Engineering",
  // Other common fields
  "Accounting",
  "Finance",
  "Marketing",
  "Economics",
  "Human Resources",
  "Psychology",
  "Public Health",
  "Education",
  "Design",
  "Architecture"
];
